### ISSUE TITLE
todo: Rewrite to use Axum instead of Actix

### ISSUE THREAD

**Issue by bananasov** [Autist69420/artist-webui#1]
## Motivation 
Axum is much simpler to use in terms of websockets.

- [ ] API Routes 
  - [x] Artist inventory route
  - [ ] Turtle info route
  - [x] General artist information route
- [x] Websockets
  - [x] Turtle connection
  - [ ] Multiple turtle support (maybe)
  - [x] Turtle communication
  - [ ] Communication between UI and backend
- [ ] Documentation
  - [ ] API Route documentation
  - [ ] Rustdoc comments
  - [ ] Websocket communication documentation
  - [ ] An actual README
